
gotchas:
	jupyter-nbconvert gotchas.ipynb --to slides
networkx:
	jupyter-nbconvert networkx.ipynb --to slides
matplotlib:
	jupyter-nbconvert matplotlib.ipynb --to slides
pandas:
	jupyter-nbconvert pandas.ipynb --to slides
numpy:
	jupyter-nbconvert numpy.ipynb --to slides
notebook:
	jupyter-nbconvert jupyter-notebooks.ipynb --to slides
introduction:
	jupyter-nbconvert introduction.ipynb --to slides
all: introduction notebook numpy pandas matplotlib networkx gotchas
